### ISSUE TITLE
AETHERHUB exporting errors

### ISSUE THREAD

**Issue by paulsnoops** [churrufli/Forgetools#1]
**The following errors are for AETHERHUB exporting**:
- [x] Brawl: Commanders are in sideboard: Should be in Command Zone
- [x] Historic Brawl: Commanders are in sideboard: Should be in Command Zone
- [x] Pioneer: Deck names broken (please see screenshot)
- [x] Modern: Deck names broken (please see screenshot)
- [x] Legacy: Deck names broken (please see screenshot)
- [x] Vintage: Deck names broken (please see screenshot)

![Forge_Tools_vnXtbc4aDY](https://user-images.githubusercontent.com/18243520/165057538-e02c321d-9b0f-4d74-b9bf-f19719aaabd8.png)

**Comment by churrufli** [comment]
fixed pls check
