### ISSUE TITLE
AETHERHUB rename some deck titles

### ISSUE THREAD

**Issue by paulsnoops** [churrufli/Forgetools#2]
**The following are requests for renaming AETHERHUB deck titles**:
- [x] [Traditional-Standard] > [Standard]
- [x] [Alchemy-BO1] > should not have "Alchemy Metagame" in the deck title
- [x] [Traditional-Alchemy] > [Alchemy]
- [x] [Historic-BO1] > should not have "Historic Metagame" in the deck title
- [x] [Traditional-Historic] > [Historic]

**Comment by churrufli** [comment]
Done, pls check
