### ISSUE TITLE
NEW categories needed please!

### ISSUE THREAD

**Issue by paulsnoops** [churrufli/Forgetools#3]
**NEW categories needed please**:

GOLDFISH:
- [x] Explorer: https://www.mtggoldfish.com/metagame/explorer#paper **could name please be [Explorer]**

AETHERHUB:
- [x] Explorer: https://aetherhub.com/Metagame/Traditional-Explorer/ **could name please be [Explorer]**
- [x] Bo1 Explorer: https://aetherhub.com/Metagame/Explorer-BO1/ **could name please be [Bo1 Explorer]**

**Comment by churrufli** [comment]
Done pls check
